-- MySQL Script generated by MySQL Workbench
-- 03/29/16 10:38:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fzstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fzstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fzstore` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fzstore` ;

-- -----------------------------------------------------
-- Table `fzstore`.`fz_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`fz_admin` (
  `aid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户自增id',
  `username` VARCHAR(45) NOT NULL COMMENT '用户名',
  `storename` VARCHAR(45) NOT NULL COMMENT '店铺名称',
  `email` VARCHAR(45) NULL COMMENT '电子邮件',
  `headimgurl` VARCHAR(255) NULL COMMENT '店铺图片地址',
  `password` CHAR(32) NOT NULL COMMENT 'MD5后的密码',
  `creat_time` INT(10) UNSIGNED NOT NULL COMMENT '注册时间',
  `money` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '账户余额',
  `status` TINYINT(8) NOT NULL COMMENT '用户状态',
  `role` TINYINT(8) UNSIGNED NOT NULL COMMENT '后台角色',
  `rate` TINYINT(8) UNSIGNED NOT NULL COMMENT '商家的分成比例',
  PRIMARY KEY (`aid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fzstore`.`fz_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`fz_goods` (
  `gid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商品自增id',
  `name` VARCHAR(45) NOT NULL COMMENT '商品名字',
  `type` TINYINT(8) UNSIGNED NOT NULL COMMENT '商品的类别',
  `left_num` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '库存数量',
  `sold_num` INT(10) NULL COMMENT '已经销售的数量',
  `format` VARCHAR(45) NULL COMMENT '商品的规则',
  `detail` TEXT NULL COMMENT '商品详情',
  `status` TINYINT(8) UNSIGNED NOT NULL COMMENT '商品状态',
  `market_price` DECIMAL(7,2) UNSIGNED NOT NULL COMMENT '市场价',
  `buy_price` DECIMAL(7,2) UNSIGNED NOT NULL COMMENT '购买价',
  `aid` INT(10) UNSIGNED NOT NULL COMMENT '所属商家',
  `rate` TINYINT(8) UNSIGNED NOT NULL COMMENT '商家的分成比例',
  PRIMARY KEY (`gid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fzstore`.`fz_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`fz_user` (
  `uid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `openid` CHAR(28) NOT NULL DEFAULT '' COMMENT '微信openid',
  `nickname` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '微信昵称',
  `headimgurl` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '微信头像地址',
  `money` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户账户余额',
  `subscribe` TINYINT(8) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户是否关注',
  `subscribe_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户最后关注时间',
  `last_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后登录时间',
  `invite_uid` INT(10) UNSIGNED NOT NULL COMMENT '邀请的用户id',
  PRIMARY KEY (`uid`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '微信用户表';


-- -----------------------------------------------------
-- Table `fzstore`.`fz_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`fz_orders` (
  `oid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单表',
  `gid` INT(10) UNSIGNED NOT NULL COMMENT '购买的商品gid',
  `buy_price` DECIMAL(7,2) UNSIGNED NOT NULL COMMENT '购买支付的价格',
  `money` DECIMAL(7,2) UNSIGNED NOT NULL COMMENT '商家收入（出去了平台所占比例）',
  `uid` INT(10) UNSIGNED NOT NULL COMMENT '所属商家id',
  `aid` INT(10) UNSIGNED NOT NULL COMMENT '所属商家id',
  `creat_time` INT(10) UNSIGNED NOT NULL COMMENT '订单创建时间',
  `buy_addr` VARCHAR(255) NOT NULL COMMENT '收货地址',
  `buy_name` VARCHAR(45) NOT NULL COMMENT '收货人姓名',
  `buy_tel` VARCHAR(45) NOT NULL COMMENT '收货人电话',
  `buy_note` VARCHAR(255) NULL COMMENT '买家备注信息',
  `ex_name` VARCHAR(45) NULL COMMENT '发货的快递公司',
  `ex_num` VARCHAR(45) NULL COMMENT '快递单号',
  `ex_time` INT(10) NULL COMMENT '发送时间',
  `status` TINYINT(8) UNSIGNED NOT NULL COMMENT '订单的状态',
  PRIMARY KEY (`oid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fzstore`.`fz_addr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`fz_addr` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `uid` INT(10) UNSIGNED NOT NULL COMMENT '所属用户',
  `name` VARCHAR(45) NULL COMMENT '收件人姓名',
  `addr` VARCHAR(45) NULL COMMENT '收货地址',
  `tel` VARCHAR(45) NULL COMMENT '收货电话',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = MyISAM
COMMENT = '用户收货地址表';


-- -----------------------------------------------------
-- Table `fzstore`.`userMoney`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`userMoney` (
  `mid` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户财务记录自增id',
  `money` DECIMAL(10,2) NOT NULL COMMENT '',
  `time` INT(10) NOT NULL COMMENT '添加时间',
  `note` VARCHAR(255) NULL COMMENT '备注信息',
  `type` TINYINT(8) UNSIGNED NOT NULL COMMENT '记录类型',
  `uid` INT(10) UNSIGNED NOT NULL COMMENT '所属用户id',
  PRIMARY KEY (`mid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fzstore`.`adminMoney`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`adminMoney` (
  `mid` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户财务记录自增id',
  `money` DECIMAL(10,2) NOT NULL COMMENT '',
  `time` INT(10) NOT NULL COMMENT '添加时间',
  `note` VARCHAR(255) NULL COMMENT '备注信息',
  `type` TINYINT(8) UNSIGNED NOT NULL COMMENT '记录类型',
  `aid` INT(10) UNSIGNED NOT NULL COMMENT '所属商家id',
  PRIMARY KEY (`mid`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fzstore`.`fz_pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`fz_pay` (
  `pid` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `creat_time` INT(10) UNSIGNED NOT NULL COMMENT '支付创建时间',
  `money` DECIMAL(7,2) UNSIGNED NOT NULL COMMENT '交易金额',
  `uid` INT(10) UNSIGNED NOT NULL COMMENT '所属用户id',
  `paytrade` BIGINT(20) UNSIGNED NOT NULL COMMENT '商家交易订单号',
  `pay_time` INT(10) UNSIGNED NOT NULL COMMENT '支付时间',
  `status` TINYINT(8) UNSIGNED NOT NULL COMMENT '支付状态',
  PRIMARY KEY (`pid`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '微信支付表单';


-- -----------------------------------------------------
-- Table `fzstore`.`fz_packets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`fz_packets` (
  `pid` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `creat_time` INT(10) UNSIGNED NOT NULL COMMENT '支付创建时间',
  `money` DECIMAL(7,2) UNSIGNED NOT NULL COMMENT '交易金额',
  `uid` INT(10) UNSIGNED NOT NULL COMMENT '所属用户id',
  `paytrade` BIGINT(20) UNSIGNED NOT NULL COMMENT '商户订单号',
  `pay_time` INT(10) UNSIGNED NOT NULL COMMENT '支付时间',
  `status` TINYINT(8) UNSIGNED NOT NULL COMMENT '支付状态',
  PRIMARY KEY (`pid`)  COMMENT '')
ENGINE = InnoDB
COMMENT = '微信红包表';


-- -----------------------------------------------------
-- Table `fzstore`.`fz_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fzstore`.`fz_config` (
  `key` VARCHAR(45) NOT NULL COMMENT '键',
  `value` TEXT NULL COMMENT '值')
ENGINE = MyISAM
COMMENT = '配置文件表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
